name: Build Project

on:
  - push
  - workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ./.github/workflows/check.yml
      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
